export interface PhonePrefix {
  label: string;
  value: string;
  short: string;
  country: string;
  country_short: string;
}

export const phonePrefixes: PhonePrefix[] = [
  { label: "Afghanistan (+93)", value: "+93", short: "AF (+93)", country: "Afghanistan", country_short: "AF" },
  { label: "Albania (+355)", value: "+355", short: "AL (+355)", country: "Albania", country_short: "AL" },
  { label: "Algeria (+213)", value: "+213", short: "DZ (+213)", country: "Algeria", country_short: "DZ" },
  { label: "Andorra (+376)", value: "+376", short: "AD (+376)", country: "Andorra", country_short: "AD" },
  { label: "Angola (+244)", value: "+244", short: "AO (+244)", country: "Angola", country_short: "AO" },
  { label: "Argentina (+54)", value: "+54", short: "AR (+54)", country: "Argentina", country_short: "AR" },
  { label: "Armenia (+374)", value: "+374", short: "AM (+374)", country: "Armenia", country_short: "AM" },
  { label: "Australia (+61)", value: "+61", short: "AU (+61)", country: "Australia", country_short: "AU" },
  { label: "Austria (+43)", value: "+43", short: "AT (+43)", country: "Austria", country_short: "AT" },
  { label: "Azerbaijan (+994)", value: "+994", short: "AZ (+994)", country: "Azerbaijan", country_short: "AZ" },
  { label: "Bahrain (+973)", value: "+973", short: "BH (+973)", country: "Bahrain", country_short: "BH" },
  { label: "Bangladesh (+880)", value: "+880", short: "BD (+880)", country: "Bangladesh", country_short: "BD" },
  { label: "Belarus (+375)", value: "+375", short: "BY (+375)", country: "Belarus", country_short: "BY" },
  { label: "Belgium (+32)", value: "+32", short: "BE (+32)", country: "Belgium", country_short: "BE" },
  { label: "Benin (+229)", value: "+229", short: "BJ (+229)", country: "Benin", country_short: "BJ" },
  { label: "Bolivia (+591)", value: "+591", short: "BO (+591)", country: "Bolivia", country_short: "BO" },
  { label: "Bosnia and Herzegovina (+387)", value: "+387", short: "BA (+387)", country: "Bosnia and Herzegovina", country_short: "BA" },
  { label: "Botswana (+267)", value: "+267", short: "BW (+267)", country: "Botswana", country_short: "BW" },
  { label: "Brazil (+55)", value: "+55", short: "BR (+55)", country: "Brazil", country_short: "BR" },
  { label: "Bulgaria (+359)", value: "+359", short: "BG (+359)", country: "Bulgaria", country_short: "BG" },
  { label: "Burkina Faso (+226)", value: "+226", short: "BF (+226)", country: "Burkina Faso", country_short: "BF" },
  { label: "Burundi (+257)", value: "+257", short: "BI (+257)", country: "Burundi", country_short: "BI" },
  { label: "Cambodia (+855)", value: "+855", short: "KH (+855)", country: "Cambodia", country_short: "KH" },
  { label: "Cameroon (+237)", value: "+237", short: "CM (+237)", country: "Cameroon", country_short: "CM" },
  { label: "Canada (+1)", value: "+1", short: "CA (+1)", country: "Canada", country_short: "CA" },
  { label: "Central African Republic (+236)", value: "+236", short: "CF (+236)", country: "Central African Republic", country_short: "CF" },
  { label: "Chad (+235)", value: "+235", short: "TD (+235)", country: "Chad", country_short: "TD" },
  { label: "Chile (+56)", value: "+56", short: "CL (+56)", country: "Chile", country_short: "CL" },
  { label: "China (+86)", value: "+86", short: "CN (+86)", country: "China", country_short: "CN" },
  { label: "Colombia (+57)", value: "+57", short: "CO (+57)", country: "Colombia", country_short: "CO" },
  { label: "Comoros (+269)", value: "+269", short: "KM (+269)", country: "Comoros", country_short: "KM" },
  { label: "Congo (+242)", value: "+242", short: "CG (+242)", country: "Congo", country_short: "CG" },
  { label: "Democratic Republic of Congo (+243)", value: "+243", short: "CD (+243)", country: "Democratic Republic of Congo", country_short: "CD" },
  { label: "Croatia (+385)", value: "+385", short: "HR (+385)", country: "Croatia", country_short: "HR" },
  { label: "Cuba (+53)", value: "+53", short: "CU (+53)", country: "Cuba", country_short: "CU" },
  { label: "Cyprus (+357)", value: "+357", short: "CY (+357)", country: "Cyprus", country_short: "CY" },
  { label: "Czech Republic (+420)", value: "+420", short: "CZ (+420)", country: "Czech Republic", country_short: "CZ" },
  { label: "Denmark (+45)", value: "+45", short: "DK (+45)", country: "Denmark", country_short: "DK" },
  { label: "Djibouti (+253)", value: "+253", short: "DJ (+253)", country: "Djibouti", country_short: "DJ" },
  { label: "Ecuador (+593)", value: "+593", short: "EC (+593)", country: "Ecuador", country_short: "EC" },
  { label: "Egypt (+20)", value: "+20", short: "EG (+20)", country: "Egypt", country_short: "EG" },
  { label: "Estonia (+372)", value: "+372", short: "EE (+372)", country: "Estonia", country_short: "EE" },
  { label: "Ethiopia (+251)", value: "+251", short: "ET (+251)", country: "Ethiopia", country_short: "ET" },
  { label: "Finland (+358)", value: "+358", short: "FI (+358)", country: "Finland", country_short: "FI" },
  { label: "France (+33)", value: "+33", short: "FR (+33)", country: "France", country_short: "FR" },
  { label: "Gabon (+241)", value: "+241", short: "GA (+241)", country: "Gabon", country_short: "GA" },
  { label: "Gambia (+220)", value: "+220", short: "GM (+220)", country: "Gambia", country_short: "GM" },
  { label: "Georgia (+995)", value: "+995", short: "GE (+995)", country: "Georgia", country_short: "GE" },
  { label: "Germany (+49)", value: "+49", short: "DE (+49)", country: "Germany", country_short: "DE" },
  { label: "Ghana (+233)", value: "+233", short: "GH (+233)", country: "Ghana", country_short: "GH" },
  { label: "Greece (+30)", value: "+30", short: "GR (+30)", country: "Greece", country_short: "GR" },
  { label: "Guinea (+224)", value: "+224", short: "GN (+224)", country: "Guinea", country_short: "GN" },
  { label: "Haiti (+509)", value: "+509", short: "HT (+509)", country: "Haiti", country_short: "HT" },
  { label: "Hungary (+36)", value: "+36", short: "HU (+36)", country: "Hungary", country_short: "HU" },
  { label: "Iceland (+354)", value: "+354", short: "IS (+354)", country: "Iceland", country_short: "IS" },
  { label: "India (+91)", value: "+91", short: "IN (+91)", country: "India", country_short: "IN" },
  { label: "Indonesia (+62)", value: "+62", short: "ID (+62)", country: "Indonesia", country_short: "ID" },
  { label: "Iran (+98)", value: "+98", short: "IR (+98)", country: "Iran", country_short: "IR" },
  { label: "Iraq (+964)", value: "+964", short: "IQ (+964)", country: "Iraq", country_short: "IQ" },
  { label: "Ireland (+353)", value: "+353", short: "IE (+353)", country: "Ireland", country_short: "IE" },
  { label: "Israel (+972)", value: "+972", short: "IL (+972)", country: "Israel", country_short: "IL" },
  { label: "Italy (+39)", value: "+39", short: "IT (+39)", country: "Italy", country_short: "IT" },
  { label: "Ivory Coast (+225)", value: "+225", short: "CI (+225)", country: "Ivory Coast", country_short: "CI" },
  { label: "Japan (+81)", value: "+81", short: "JP (+81)", country: "Japan", country_short: "JP" },
  { label: "Jordan (+962)", value: "+962", short: "JO (+962)", country: "Jordan", country_short: "JO" },
  { label: "Kazakhstan (+7)", value: "+7", short: "KZ (+7)", country: "Kazakhstan", country_short: "KZ" },
  { label: "Kenya (+254)", value: "+254", short: "KE (+254)", country: "Kenya", country_short: "KE" },
  { label: "Kuwait (+965)", value: "+965", short: "KW (+965)", country: "Kuwait", country_short: "KW" },
  { label: "Latvia (+371)", value: "+371", short: "LV (+371)", country: "Latvia", country_short: "LV" },
  { label: "Lebanon (+961)", value: "+961", short: "LB (+961)", country: "Lebanon", country_short: "LB" },
  { label: "Libya (+218)", value: "+218", short: "LY (+218)", country: "Libya", country_short: "LY" },
  { label: "Lithuania (+370)", value: "+370", short: "LT (+370)", country: "Lithuania", country_short: "LT" },
  { label: "Luxembourg (+352)", value: "+352", short: "LU (+352)", country: "Luxembourg", country_short: "LU" },
  { label: "Madagascar (+261)", value: "+261", short: "MG (+261)", country: "Madagascar", country_short: "MG" },
  { label: "Malaysia (+60)", value: "+60", short: "MY (+60)", country: "Malaysia", country_short: "MY" },
  { label: "Mali (+223)", value: "+223", short: "ML (+223)", country: "Mali", country_short: "ML" },
  { label: "Malta (+356)", value: "+356", short: "MT (+356)", country: "Malta", country_short: "MT" },
  { label: "Mauritania (+222)", value: "+222", short: "MR (+222)", country: "Mauritania", country_short: "MR" },
  { label: "Mexico (+52)", value: "+52", short: "MX (+52)", country: "Mexico", country_short: "MX" },
  { label: "Moldova (+373)", value: "+373", short: "MD (+373)", country: "Moldova", country_short: "MD" },
  { label: "Monaco (+377)", value: "+377", short: "MC (+377)", country: "Monaco", country_short: "MC" },
  { label: "Morocco (+212)", value: "+212", short: "MA (+212)", country: "Morocco", country_short: "MA" },
  { label: "Myanmar (+95)", value: "+95", short: "MM (+95)", country: "Myanmar", country_short: "MM" },
  { label: "Nepal (+977)", value: "+977", short: "NP (+977)", country: "Nepal", country_short: "NP" },
  { label: "Netherlands (+31)", value: "+31", short: "NL (+31)", country: "Netherlands", country_short: "NL" },
  { label: "New Zealand (+64)", value: "+64", short: "NZ (+64)", country: "New Zealand", country_short: "NZ" },
  { label: "Nicaragua (+505)", value: "+505", short: "NI (+505)", country: "Nicaragua", country_short: "NI" },
  { label: "Niger (+227)", value: "+227", short: "NE (+227)", country: "Niger", country_short: "NE" },
  { label: "Nigeria (+234)", value: "+234", short: "NG (+234)", country: "Nigeria", country_short: "NG" },
  { label: "Norway (+47)", value: "+47", short: "NO (+47)", country: "Norway", country_short: "NO" },
  { label: "Pakistan (+92)", value: "+92", short: "PK (+92)", country: "Pakistan", country_short: "PK" },
  { label: "Panama (+507)", value: "+507", short: "PA (+507)", country: "Panama", country_short: "PA" },
  { label: "Peru (+51)", value: "+51", short: "PE (+51)", country: "Peru", country_short: "PE" },
  { label: "Philippines (+63)", value: "+63", short: "PH (+63)", country: "Philippines", country_short: "PH" },
  { label: "Poland (+48)", value: "+48", short: "PL (+48)", country: "Poland", country_short: "PL" },
  { label: "Portugal (+351)", value: "+351", short: "PT (+351)", country: "Portugal", country_short: "PT" },
  { label: "Qatar (+974)", value: "+974", short: "QA (+974)", country: "Qatar", country_short: "QA" },
  { label: "Romania (+40)", value: "+40", short: "RO (+40)", country: "Romania", country_short: "RO" },
  { label: "Russia (+7)", value: "+7", short: "RU (+7)", country: "Russia", country_short: "RU" },
  { label: "Rwanda (+250)", value: "+250", short: "RW (+250)", country: "Rwanda", country_short: "RW" },
  { label: "Saudi Arabia (+966)", value: "+966", short: "SA (+966)", country: "Saudi Arabia", country_short: "SA" },
  { label: "Senegal (+221)", value: "+221", short: "SN (+221)", country: "Senegal", country_short: "SN" },
  { label: "Serbia (+381)", value: "+381", short: "RS (+381)", country: "Serbia", country_short: "RS" },
  { label: "Singapore (+65)", value: "+65", short: "SG (+65)", country: "Singapore", country_short: "SG" },
  { label: "Slovakia (+421)", value: "+421", short: "SK (+421)", country: "Slovakia", country_short: "SK" },
  { label: "Slovenia (+386)", value: "+386", short: "SI (+386)", country: "Slovenia", country_short: "SI" },
  { label: "South Africa (+27)", value: "+27", short: "ZA (+27)", country: "South Africa", country_short: "ZA" },
  { label: "South Korea (+82)", value: "+82", short: "KR (+82)", country: "South Korea", country_short: "KR" },
  { label: "Spain (+34)", value: "+34", short: "ES (+34)", country: "Spain", country_short: "ES" },
  { label: "Sweden (+46)", value: "+46", short: "SE (+46)", country: "Sweden", country_short: "SE" },
  { label: "Switzerland (+41)", value: "+41", short: "CH (+41)", country: "Switzerland", country_short: "CH" },
  { label: "Thailand (+66)", value: "+66", short: "TH (+66)", country: "Thailand", country_short: "TH" },
  { label: "Tunisia (+216)", value: "+216", short: "TN (+216)", country: "Tunisia", country_short: "TN" },
  { label: "Turkey (+90)", value: "+90", short: "TR (+90)", country: "Turkey", country_short: "TR" },
  { label: "Uganda (+256)", value: "+256", short: "UG (+256)", country: "Uganda", country_short: "UG" },
  { label: "Ukraine (+380)", value: "+380", short: "UA (+380)", country: "Ukraine", country_short: "UA" },
  { label: "United Arab Emirates (+971)", value: "+971", short: "AE (+971)", country: "United Arab Emirates", country_short: "AE" },
  { label: "United Kingdom (+44)", value: "+44", short: "GB (+44)", country: "United Kingdom", country_short: "GB" },
  { label: "United States (+1)", value: "+1", short: "US (+1)", country: "United States", country_short: "US" },
  { label: "Uruguay (+598)", value: "+598", short: "UY (+598)", country: "Uruguay", country_short: "UY" },
  { label: "Venezuela (+58)", value: "+58", short: "VE (+58)", country: "Venezuela", country_short: "VE" },
  { label: "Vietnam (+84)", value: "+84", short: "VN (+84)", country: "Vietnam", country_short: "VN" },
  { label: "Yemen (+967)", value: "+967", short: "YE (+967)", country: "Yemen", country_short: "YE" },
  { label: "Zambia (+260)", value: "+260", short: "ZM (+260)", country: "Zambia", country_short: "ZM" },
  { label: "Zimbabwe (+263)", value: "+263", short: "ZW (+263)", country: "Zimbabwe", country_short: "ZW" }
];